name: Auto Minifier CSS

on: push

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:1.0.3
        with:
          directory: 'src'
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
